# ============================================================
# QUASAR — Deploy Layer
# qsr_deploy()
# "From analysis to Shiny app or API — one line."
# ============================================================

#' Generate a Shiny app or Plumber API from your analysis
#'
#' Creates a ready-to-run Shiny dashboard or REST API from the current
#' QUASAR context (data, models, plots, tables). No Shiny/Plumber
#' knowledge required.
#'
#' @param type Character. Deploy type: "shiny", "api". Default "shiny".
#' @param title Character. App/API title. Default "QUASAR Dashboard".
#' @param path Character. Directory to write the app/API files. Default
#'   "deploy/".
#' @param models Character vector. Model names from context to include.
#'   Default NULL (all models).
#' @param include Character vector. What to include: "data", "models",
#'   "plots", "tables", "predictions". Default all.
#' @param theme Character. Shiny theme: "default", "darkly", "flatly",
#'   "cosmo". Default "flatly".
#' @param launch Logical. Launch the app after generating? Default FALSE.
#'
#' @return The path to the generated app (invisibly).
#'
#' @examples
#' \dontrun{
#' qsr_data(mtcars)
#' qsr_model(mpg ~ wt + hp)
#' qsr_table()
#' qsr_plot(type = "coefficient")
#'
#' # Generate Shiny dashboard
#' qsr_deploy()
#'
#' # Generate REST API
#' qsr_deploy(type = "api", path = "my_api/")
#'
#' # Generate and launch
#' qsr_deploy(launch = TRUE)
#' }
#'
#' @export
qsr_deploy <- function(type = c("shiny", "api"),
                       title = "QUASAR Dashboard",
                       path = "deploy",
                       models = NULL,
                       include = c("data", "models", "plots",
                                   "tables", "predictions"),
                       theme = c("flatly", "darkly", "cosmo", "default"),
                       launch = FALSE) {

  type <- match.arg(type)
  theme <- match.arg(theme)

  # Validate we have something to deploy
  ctx_data <- .qsr_context$get_data()
  ctx_models <- .qsr_context$get_models()

  if (is.null(ctx_data) && length(ctx_models) == 0) {
    cli::cli_abort(c(
      "Nothing to deploy. Context is empty.",
      "i" = "Use {.fn qsr_data}, {.fn qsr_model} first."
    ))
  }

  # Filter models if specified
  if (!is.null(models) && length(ctx_models) > 0) {
    ctx_models <- ctx_models[names(ctx_models) %in% models]
  }

  # Create output directory
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)

  # Save context data for the app
  save_path <- file.path(path, "quasar_context.rds")
  saveRDS(list(
    data = ctx_data,
    models = ctx_models
  ), save_path)

  if (type == "shiny") {
    .qsr_deploy_shiny(path, title, theme, include, ctx_data, ctx_models)
  } else {
    .qsr_deploy_api(path, title, include, ctx_data, ctx_models)
  }

  cli::cli_alert_success("Generated {.strong {type}} app in {.file {path}/}")

  if (launch && type == "shiny") {
    .qsr_require("shiny", "to launch the app")
    cli::cli_alert_info("Launching Shiny app...")
    shiny::runApp(path)
  }

  invisible(path)
}


# ============================================================
# Internal: Shiny app generator
# ============================================================

#' @keywords internal
.qsr_deploy_shiny <- function(path, title, theme, include, data, models) {
  .qsr_require("shiny", "to generate Shiny apps")

  # Determine what tabs to create
  has_data <- !is.null(data) && "data" %in% include
  has_models <- length(models) > 0 && "models" %in% include
  has_predictions <- has_models && "predictions" %in% include
  num_cols <- if (has_data) names(data)[vapply(data, is.numeric, logical(1))] else character()
  all_cols <- if (has_data) names(data) else character()

  # Build UI code
  ui_code <- .qsr_shiny_ui(title, theme, has_data, has_models,
                            has_predictions, num_cols, all_cols, models)

  # Build server code
  server_code <- .qsr_shiny_server(has_data, has_models, has_predictions,
                                    num_cols, models)

  # Write app.R
  app_code <- paste0(
    '# Generated by QUASAR — qsr_deploy()\n',
    '# Do not edit manually — regenerate with qsr_deploy()\n\n',
    'library(shiny)\n',
    if (theme != "default") 'library(bslib)\n' else '',
    'library(DT)\n',
    'library(ggplot2)\n\n',
    '# Load QUASAR context\n',
    'ctx <- readRDS("quasar_context.rds")\n',
    'data <- ctx$data\n',
    'models <- ctx$models\n\n',
    ui_code, '\n\n',
    server_code, '\n\n',
    'shinyApp(ui, server)\n'
  )

  writeLines(app_code, file.path(path, "app.R"))
  cli::cli_alert_info("Created {.file app.R}")
}


#' @keywords internal
.qsr_shiny_ui <- function(title, theme, has_data, has_models,
                           has_predictions, num_cols, all_cols, models) {

  theme_code <- if (theme != "default") {
    paste0('  theme = bslib::bs_theme(bootswatch = "', theme, '"),\n')
  } else ""

  tabs <- character()

  if (has_data) {
    tabs <- c(tabs, paste0(
      '    tabPanel("Data",\n',
      '      fluidRow(\n',
      '        column(12, h4(paste("Dataset:", nrow(data), "rows x", ncol(data), "cols")),\n',
      '               DT::dataTableOutput("data_table"))\n',
      '      )\n',
      '    )'
    ))

    tabs <- c(tabs, paste0(
      '    tabPanel("Explorer",\n',
      '      sidebarLayout(\n',
      '        sidebarPanel(width = 3,\n',
      '          selectInput("x_var", "X axis:", choices = names(data)),\n',
      '          selectInput("y_var", "Y axis:", choices = names(data),\n',
      '                      selected = names(data)[min(2, ncol(data))]),\n',
      '          selectInput("color_var", "Color:", choices = c("None", names(data)))\n',
      '        ),\n',
      '        mainPanel(width = 9, plotOutput("explorer_plot", height = "500px"))\n',
      '      )\n',
      '    )'
    ))
  }

  if (has_models) {
    model_names <- paste0('"', names(models), '"', collapse = ", ")
    tabs <- c(tabs, paste0(
      '    tabPanel("Models",\n',
      '      sidebarLayout(\n',
      '        sidebarPanel(width = 3,\n',
      '          selectInput("model_name", "Model:", choices = c(', model_names, ')),\n',
      '          verbatimTextOutput("model_summary")\n',
      '        ),\n',
      '        mainPanel(width = 9, plotOutput("model_plot", height = "500px"))\n',
      '      )\n',
      '    )'
    ))
  }

  if (has_predictions) {
    tabs <- c(tabs, paste0(
      '    tabPanel("Predictions",\n',
      '      sidebarLayout(\n',
      '        sidebarPanel(width = 3,\n',
      '          selectInput("pred_model", "Model:", choices = c(', model_names, ')),\n',
      '          actionButton("predict_btn", "Generate Predictions", class = "btn-primary")\n',
      '        ),\n',
      '        mainPanel(width = 9,\n',
      '          DT::dataTableOutput("pred_table"),\n',
      '          plotOutput("pred_plot", height = "400px")\n',
      '        )\n',
      '      )\n',
      '    )'
    ))
  }

  tabs_str <- paste(tabs, collapse = ",\n")

  paste0(
    'ui <- navbarPage(\n',
    '  title = "', title, '",\n',
    theme_code,
    tabs_str, '\n',
    ')'
  )
}


#' @keywords internal
.qsr_shiny_server <- function(has_data, has_models, has_predictions,
                               num_cols, models) {

  parts <- character()

  if (has_data) {
    parts <- c(parts, paste0(
      '  output$data_table <- DT::renderDataTable({\n',
      '    DT::datatable(data, options = list(pageLength = 20, scrollX = TRUE))\n',
      '  })\n\n',
      '  output$explorer_plot <- renderPlot({\n',
      '    p <- ggplot(data, aes(x = .data[[input$x_var]], y = .data[[input$y_var]]))\n',
      '    if (input$color_var != "None") {\n',
      '      p <- p + geom_point(aes(color = .data[[input$color_var]]), size = 3, alpha = 0.7)\n',
      '    } else {\n',
      '      p <- p + geom_point(size = 3, alpha = 0.7, color = "#2C3E50")\n',
      '    }\n',
      '    p + theme_minimal(base_size = 14) + labs(title = paste(input$y_var, "vs", input$x_var))\n',
      '  })'
    ))
  }

  if (has_models) {
    parts <- c(parts, paste0(
      '  output$model_summary <- renderPrint({\n',
      '    m <- models[[input$model_name]]\n',
      '    if (inherits(m, "lm")) summary(m)\n',
      '    else if (inherits(m, "ranger")) print(m)\n',
      '    else if (inherits(m, "nnet")) summary(m)\n',
      '    else print(m)\n',
      '  })\n\n',
      '  output$model_plot <- renderPlot({\n',
      '    m <- models[[input$model_name]]\n',
      '    if (inherits(m, "lm")) {\n',
      '      par(mfrow = c(2, 2))\n',
      '      plot(m)\n',
      '    } else if (inherits(m, "rpart") && requireNamespace("rpart.plot", quietly = TRUE)) {\n',
      '      rpart.plot::rpart.plot(m)\n',
      '    }\n',
      '  })'
    ))
  }

  if (has_predictions) {
    parts <- c(parts, paste0(
      '  pred_data <- eventReactive(input$predict_btn, {\n',
      '    m <- models[[input$pred_model]]\n',
      '    if (inherits(m, "lm")) {\n',
      '      preds <- predict(m, newdata = data)\n',
      '      data.frame(row = seq_len(nrow(data)), actual = model.response(model.frame(m)),\n',
      '                 predicted = preds, residual = model.response(model.frame(m)) - preds)\n',
      '    } else {\n',
      '      data.frame(message = "Predictions not available for this model type")\n',
      '    }\n',
      '  })\n\n',
      '  output$pred_table <- DT::renderDataTable({\n',
      '    DT::datatable(pred_data(), options = list(pageLength = 15))\n',
      '  })\n\n',
      '  output$pred_plot <- renderPlot({\n',
      '    pd <- pred_data()\n',
      '    if ("actual" %in% names(pd)) {\n',
      '      ggplot(pd, aes(x = actual, y = predicted)) +\n',
      '        geom_point(alpha = 0.7, size = 3, color = "#2C3E50") +\n',
      '        geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +\n',
      '        theme_minimal(base_size = 14) +\n',
      '        labs(title = "Actual vs Predicted", x = "Actual", y = "Predicted")\n',
      '    }\n',
      '  })'
    ))
  }

  parts_str <- paste(parts, collapse = "\n\n")

  paste0(
    'server <- function(input, output, session) {\n',
    parts_str, '\n',
    '}'
  )
}


# ============================================================
# Internal: Plumber API generator
# ============================================================

#' @keywords internal
.qsr_deploy_api <- function(path, title, include, data, models) {

  api_code <- paste0(
    '# Generated by QUASAR — qsr_deploy(type = "api")\n',
    '# Run with: plumber::pr_run(plumber::pr("plumber.R"))\n\n',
    'library(plumber)\n\n',
    '# Load QUASAR context\n',
    'ctx <- readRDS("quasar_context.rds")\n',
    'data <- ctx$data\n',
    'models <- ctx$models\n\n',
    '#* @apiTitle ', title, '\n',
    '#* @apiDescription REST API generated by QUASAR\n\n'
  )

  if ("data" %in% include && !is.null(data)) {
    api_code <- paste0(api_code,
      '#* Get dataset info\n',
      '#* @get /data/info\n',
      'function() {\n',
      '  list(rows = nrow(data), cols = ncol(data),\n',
      '       columns = names(data),\n',
      '       types = vapply(data, class, character(1)))\n',
      '}\n\n',
      '#* Get data (with optional limit)\n',
      '#* @param limit Number of rows to return\n',
      '#* @get /data\n',
      'function(limit = 100) {\n',
      '  limit <- min(as.integer(limit), nrow(data))\n',
      '  head(data, limit)\n',
      '}\n\n',
      '#* Get summary statistics\n',
      '#* @get /data/summary\n',
      'function() {\n',
      '  num_cols <- names(data)[vapply(data, is.numeric, logical(1))]\n',
      '  lapply(num_cols, function(col) {\n',
      '    x <- data[[col]]\n',
      '    list(column = col, mean = mean(x, na.rm = TRUE),\n',
      '         sd = sd(x, na.rm = TRUE), min = min(x, na.rm = TRUE),\n',
      '         max = max(x, na.rm = TRUE), na_count = sum(is.na(x)))\n',
      '  })\n',
      '}\n\n'
    )
  }

  if ("models" %in% include && length(models) > 0) {
    api_code <- paste0(api_code,
      '#* List available models\n',
      '#* @get /models\n',
      'function() {\n',
      '  lapply(names(models), function(nm) {\n',
      '    m <- models[[nm]]\n',
      '    list(name = nm, type = class(m)[1])\n',
      '  })\n',
      '}\n\n'
    )

    if ("predictions" %in% include) {
      api_code <- paste0(api_code,
        '#* Get predictions from a model\n',
        '#* @param model_name Name of the model\n',
        '#* @post /predict\n',
        'function(req, model_name = "last") {\n',
        '  m <- models[[model_name]]\n',
        '  if (is.null(m)) return(list(error = "Model not found"))\n',
        '  newdata <- tryCatch(jsonlite::fromJSON(req$postBody),\n',
        '                      error = function(e) data)\n',
        '  if (inherits(m, "lm")) {\n',
        '    preds <- predict(m, newdata = as.data.frame(newdata))\n',
        '    list(predictions = as.list(preds))\n',
        '  } else {\n',
        '    list(error = "Prediction not supported for this model type")\n',
        '  }\n',
        '}\n\n'
      )
    }
  }

  api_code <- paste0(api_code,
    '#* Health check\n',
    '#* @get /health\n',
    'function() {\n',
    '  list(status = "ok", framework = "QUASAR",\n',
    '       timestamp = Sys.time())\n',
    '}\n'
  )

  writeLines(api_code, file.path(path, "plumber.R"))
  cli::cli_alert_info("Created {.file plumber.R}")
}
