# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rquasar_wrappers", use_symbols = TRUE, package_name = "rquasar")

#' @usage NULL
#' @useDynLib rquasar, .registration = TRUE
NULL

#' Read a CSV file using Polars (10-30x faster than read.csv).
#' @param path Character. Path to the CSV file.
#' @param n_rows Integer or NULL. Max rows to read.
#' @param separator Character. Field delimiter (first byte is used, e.g. "|", ",", or a tab).
#' @param columns Character vector or NULL. Columns to read; when given, Polars pushes
#'   the projection down to the scan and only reads those columns from disk.
#' @export
rust_read_csv <- function(path, n_rows, separator, columns) .Call(wrap__rust_read_csv, path, n_rows, separator, columns)

rust_sink_parquet <- function(path, out, separator, columns) .Call(wrap__rust_sink_parquet, path, out, separator, columns)

rust_transcode_utf8 <- function(path, out, from) .Call(wrap__rust_transcode_utf8, path, out, from)

#' Read a Parquet file using Polars.
#' @param path Character. Path to the Parquet file.
#' @export
rust_read_parquet <- function(path) .Call(wrap__rust_read_parquet, path)

#' Fast summary statistics for numeric columns.
#' @param path Character. Path to CSV file.
#' @export
rust_describe <- function(path) .Call(wrap__rust_describe, path)

#' Fast group-by aggregation.
#' @param path Character. Path to CSV file.
#' @param group_col Character. Column to group by.
#' @param agg_col Character. Column to aggregate.
#' @param agg_fn Character. One of: mean, sum, count, min, max, std.
#' @export
rust_group_agg <- function(path, group_col, agg_col, agg_fn) .Call(wrap__rust_group_agg, path, group_col, agg_col, agg_fn)

#' Fast filter rows.
#' @param path Character. Path to CSV file.
#' @param col_name Character. Column to filter on.
#' @param op Character. One of: gt, lt, gte, lte, eq, neq.
#' @param value Double. Value to compare against.
#' @export
rust_filter <- function(path, col_name, op, value) .Call(wrap__rust_filter, path, col_name, op, value)

#' Fast sort rows.
#' @param path Character. Path to CSV file.
#' @param by Character. Column to sort by.
#' @param descending Logical.
#' @export
rust_sort <- function(path, by, descending) .Call(wrap__rust_sort, path, by, descending)


# nolint end
