[package]
name = 'rquasar'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = ['staticlib']
name = 'rquasar'

[dependencies]
extendr-api = '0.8.1'
polars = { version = '0.46', default-features = false, features = [
    'csv',
    'parquet',
    'lazy',
    'streaming',
    'dtype-full',
    'strings',
    'temporal',
    'round_series',
    'is_in',
    'abs',
    'cum_agg',
    'log',
] }

[profile.release]
lto = true
codegen-units = 1
